# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc6fd0b8afa5e12f70eac5c9bbefcec53b75b3bedb2ae40dc788bbc58e655c0df2305f5e3ca32ca9d3d6cd853a5eee28cd323085450e390a9cf387e377955f0c

test:
  secret_key_base: 94b8b9b590e385912cccbab10d7bc7e48b118d44d3c87c4c9ccadf7c89126d47a94a8810b5483d0df9108318a1721f8e788796851c79063316f6a7697527c81e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
